@baseUrl = http://localhost:8080

@urlPath = api/v1

###

POST {{baseUrl}}/{{urlPath}}/post
Content-Type: application/json
Accept: application/json
withCredentials: true

{
    "post": "A sample Post for testig.",
    "bgColor": "#4aa1f3",
    "privacy": "Public",
    "gifUrl": "",
    "profilePicture": "https://res.cloudinary.com/duywfhwqq/image/upload/v1679569927/641c340560c9ba1397554bd7",
    "feelings": "happy"
}
